version: "3.8"

services:
  nginx:
    image: "nginx:stable-alpine"
    container_name: nginx
    ports:
      - "8001:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./laravel-app:/var/www/laravel
    networks:
      - app-network
    depends_on:
      - php

  php:
    build:
      context: dockerfiles
      dockerfile: php.Dockerfile
    container_name: php
    volumes:
      - ./laravel-app:/var/www/laravel
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  python-api:
    build:
      context: ./python-api
    container_name: python-api
    ports:
      - 8002:8000
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysql
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    networks:
      - app-network

  composer:
    build:
      context: ./dockerfiles
      dockerfile: composer.Dockerfile
    container_name: composer
    volumes:
      - ./laravel-app:/var/www/laravel
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
