version: "3.8"

services:
  nginx:
    image: "nginx:stable-alpine"
    container_name: nginx
    ports:
      - "8001:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./laravel-app:/var/www/laravel
    networks:
      - app-network
    depends_on:
      - php

  php:
    build:
      context: dockerfiles
      dockerfile: php.Dockerfile
    container_name: php
    volumes:
      - ./laravel-app:/var/www/laravel
    networks:
      - app-network

  python-api:
    build:
      context: ./python-api
    container_name: python-api
    ports:
      - 8002:8000
    networks:
      - app-network

  composer:
    build:
      context: ./dockerfiles
      dockerfile: composer.Dockerfile
    container_name: composer
    volumes:
      - ./laravel-app:/var/www/laravel
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
